org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=0.0.1-ALPHA
group=net.morthen
java_version=25

modrinth_id=nH4fIN8E
curseforge_id=1202315

# Common
minecraft_version=26.2

mod_id=template
mod_name=Template
mod_author=Morthen
mod_license=MIT
mod_description=

neoform=26.2-2
neoforge=26.2.0.54-beta
fabric_api=0.156.0+26.2
fabric_loader=0.19.3
forge=65.1.0

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Multiloader-Template
issues_url=https://github.com/Morthen-Mods/Multiloader-Template/issues