org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=0.0.7-ALPHA
group=net.morthen
java_version=25

modrinth_id=nH4fIN8E
curseforge_id=1202315

# Common
minecraft_version=26.1.2

mod_id=template
mod_name=Template
mod_author=Morthen
mod_license=MIT
mod_description=

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Multiloader-Template
issues_url=https://github.com/Morthen-Mods/Multiloader-Template/issues