org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false


version=0.0.7-ALPHA
group=net.morthen.example
java_version=25
modrinth_id=nH4fIN8E
curseforge_id=1202315

# Common
minecraft_version=26.1.2
mod_name=ExampleMod
mod_author=Morthen
mod_id=example
license=MIT
credits=
description=


neo_form_version=26.1.2-1
fabric_version=0.155.2
fabric_loader_version=0.19.3
forge_version=64.0.14
neoforge_version=26.1.2.71
